### ISSUE TITLE
Action Recognition - Corrupted Videos [SOLVED]

### ISSUE THREAD

**Issue by ycybiubiu** [VIPriors/vipriors-challenges-toolkit#58] opened 2022-07-18 06:34 UTC
1、The download data is damaged, is it a download problem or a data problem?
2、Submission results require groundruths.txt, but github only gives the format of submission.txt, without mentioning groundruths.txt.

**Comment by rjbruin** [comment] 2022-07-18 08:08
Hi, about the first question: did you use the URLs as in this file: https://github.com/VIPriors/vipriors-challenges-toolkit/blob/master/action-recognition/data/Kinetics400ViPriors_urls.txt?

About the second question: you cannot evaluate the model on your own machine. Submit a submission file to the Codalab server, and we calculate the test score on the server. You don't need the groundtruths to create a submission file.

**Comment by ycybiubiu** [comment] 2022-07-18 08:22
Thanks for your reply! 
About first question, I did download it in this file.I'll download again without disconnecting, and I'll get back to you if there's still a problem.

The second question should be that I didn't describe it clearly just now. My problem is that when submitting the results in the verification stage, I only compress the submission.txt in the root directory and submit it, and the system displays the following error:





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VIPriors/vipriors-challenges-toolkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VIPriors/vipriors-challenges-toolkit] Action Recognition Track Questions (Issue #58)





 
Hi, about the first question: did you use the URLs as in this file: https://github.com/VIPriors/vipriors-challenges-toolkit/blob/master/action-recognition/data/Kinetics400ViPriors_urls.txt?
 
About the second question: you cannot evaluate the model on your own machine. Submit a submission file to the Codalab server, and we calculate the test score on the server. You don't need the groundtruths to create a submission file.

**Comment by rjbruin** [comment] 2022-07-18 08:37
Hi, I think something went wrong posting the error message. Can you try again?

**Comment by ycybiubiu** [comment] 2022-07-18 08:51
I submitted with the validation set results randomly generated by the baseline, but still reported an error：

Unable to find image 'rjbruin/vipriors-object-detection-evaluation:1.1' locally
1.1: Pulling from rjbruin/vipriors-object-detection-evaluation
4ae16bd47783: Already exists
46d3909aefd6: Pulling fs layer
b8fd74fabe0f: Pulling fs layer
836d375308d1: Pulling fs layer
338996cb2698: Pulling fs layer
f98d8d5f66de: Pulling fs layer
7d209ed0cc7b: Pulling fs layer
190e5781d107: Pulling fs layer
0499accd4745: Pulling fs layer
d9aa9a503246: Pulling fs layer
77f2dbd77c97: Pulling fs layer
7d209ed0cc7b: Waiting
190e5781d107: Waiting
0499accd4745: Waiting
d9aa9a503246: Waiting
338996cb2698: Waiting
77f2dbd77c97: Waiting
f98d8d5f66de: Waiting
836d375308d1: Verifying Checksum
836d375308d1: Download complete
f98d8d5f66de: Verifying Checksum
f98d8d5f66de: Download complete
docker: write /var/lib/docker/tmp/GetImageBlob313120484: no space left on device.
See 'docker run --help'.

**Comment by rjbruin** [comment] 2022-07-18 08:52
Ah, this seems to be an issue with the serve environment. Let me investigate this.

**Comment by rjbruin** [comment] 2022-07-18 11:35
Can you try again? The maintainers say the issue should be fixed now.

**Comment by ycybiubiu** [comment] 2022-07-18 11:41
I retried the validation set submission and reported the following error:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpn7ElWN/run/program/eval_moducf101.py", line 137, in 
    top_k_acc(pred_file, gt_file, k, outdir)
  File "/tmp/codalab/tmpn7ElWN/run/program/eval_moducf101.py", line 61, in top_k_acc
    with open(gt_file, 'r') as gt_f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpn7ElWN/run/input/ref/groundtruths.txt'

**Comment by rjbruin** [comment] 2022-07-18 11:59
Ah, so something appeared to be wrong with the groundtruth data on the server. I fixed it now, I think. Can you check?

**Comment by ycybiubiu** [comment] 2022-07-18 12:03
It worked,thank you!

**Comment by rjbruin** [comment] 2022-07-18 12:04
Great! Good luck with the competition! :)

**Comment by ycybiubiu** [comment] 2022-07-20 02:25
Hi, The data download problem we talked about earlier, I tried to download it twice, both with corrupted video.

**Comment by rjbruin** [comment] 2022-07-20 07:42
Let me try to reproduce your issue.

**Comment by bapmbr** [comment] 2022-07-20 11:27
Hi

We have checked again both options we have to download the Kinetics400ViPriors dataset for the Action Recognition challenge.

Both Google Storage and SurfDrive options are correctly working. We did not find any video/link/file corrupted. From both methods, the quickest option is Google Storage. So we recommend you to follow the guidelines here https://github.com/VIPriors/vipriors-challenges-toolkit/tree/master/action-recognition/data to get the dataset.

Please, give us more information. We want to help you! Although we believe something might be happening on your side.

**Comment by ycybiubiu** [comment] 2022-07-20 11:45
Have you used opencv or other software to traverse the downloaded data?

**Comment by bapmbr** [comment] 2022-07-26 07:04
Can you tell us which video files did you find to be corrupted?

**Comment by ycybiubiu** [comment] 2022-07-26 07:07
/data/train/anRCPrxyWh.mp4
/data/train/aYnZtMOAFf.mp4
/data/train/IncwaePmrd.mp4
/data/train/yyNQGzSeZN.mp4
/data/train/ayCtOFxyCN.mp4
/data/train/niybFpPHhY.mp4
/data/train/VbntHfudHe.mp4
/data/train/JypTrexwGs.mp4
/data/train/HpgNvvIXcB.mp4
/data/train/nhhNbCPMuN.mp4
/data/train/UDkhQjpFBk.mp4
/data/train/aygjDTTwlb.mp4
/data/train/LAKxJAueyq.mp4
/data/train/fwuwTkyQZJ.mp4
/data/train/QhUOMnexaM.mp4
/data/train/odowgURdKV.mp4
/data/train/QFUdHGodfG.mp4
/data/train/dxQkeqgFRi.mp4
/data/train/TcYotooVQN.mp4
/data/train/GzOQMyvnRF.mp4
/data/train/LMtcSvWsNd.mp4
/data/train/jrNXcMCaJr.mp4
/data/train/xmhrNtNiww.mp4
/data/train/MIdozPtkeu.mp4
/data/train/oCmUNyUDSI.mp4
/data/train/KLafkdZlhp.mp4
/data/train/oKqndhPtlP.mp4
/data/train/ZshcfyhFNu.mp4
/data/train/kpxTHiEkdN.mp4
/data/train/WXIIUafJBl.mp4
/data/train/FdSDqiDsQZ.mp4
/data/train/uGvvyajEuk.mp4
/data/train/nRhJPfkRnX.mp4
/data/train/bfTwHoYqOd.mp4
/data/train/Faviwoahpy.mp4
/data/train/oodNuNhEVm.mp4
/data/train/sFpLARRjgR.mp4
/data/train/cBUJcazBdH.mp4
/data/train/QAbILiyyxb.mp4
/data/train/KxgTwqloNN.mp4
/data/train/kQdMDFczLs.mp4
/data/train/XqJFkShfWL.mp4
/data/train/YIiUUDkukS.mp4
/data/train/GZBnmODjQY.mp4
/data/train/JqTfANpDWM.mp4
/data/train/lRQiWKTfFN.mp4
/data/train/vICdRjXAYy.mp4
/data/train/FRRprzCjuG.mp4
/data/train/PPfBpykRIx.mp4
/data/train/oHxnvVbQBW.mp4
/data/train/RMdKyEXDIq.mp4
/data/train/giJmkfwWMh.mp4
/data/train/MBUwLrfUyn.mp4
/data/train/XjthXEIXgV.mp4
/data/train/qiYsfXSHvf.mp4
/data/train/szldeiXoSI.mp4
/data/train/HCsklUexqY.mp4
/data/train/pahxEDBOGj.mp4
/data/train/uhOENGVLPS.mp4
/data/train/WSblRDTzpO.mp4
/data/train/mBuZHZqWjP.mp4
/data/train/yBkGQybSmZ.mp4
/data/train/VPlzNCHylq.mp4
/data/train/zFhPGfOZLi.mp4
/data/train/AJtkcceoXB.mp4
/data/train/vLhlcAeOHC.mp4
/data/train/QANKfCeqpA.mp4
/data/train/hKECfRaNlR.mp4
/data/train/tTPZIyHWLI.mp4
/data/train/ZVNrEfWtiJ.mp4
/data/train/fkWzMrYaKO.mp4
/data/train/HlGZoOxOIM.mp4
/data/train/cAcDCRvEbu.mp4
/data/train/FRElLDmpaI.mp4
/data/train/evufDCYMQw.mp4
/data/train/itRydwQmBK.mp4
/data/train/iIEdvSQSEb.mp4
/data/train/NeQGSwWQNo.mp4
/data/train/LvzZErAMGc.mp4
/data/train/KCiNhEHaJJ.mp4
/data/train/qrxdFuRjre.mp4
/data/train/wxeoRKXCJl.mp4
/data/train/viwBvCgGBB.mp4
/data/train/EHUsseiqmK.mp4
/data/train/QzJHfddlMN.mp4
/data/train/aDPeCNlTQU.mp4
/data/train/cmekmHQfoE.mp4
/data/train/kDlqMUMPUW.mp4
/data/train/DLScQonKer.mp4
/data/train/rwYEPimelU.mp4
/data/train/XmAArbvESP.mp4
/data/train/oCPTWJzNtN.mp4
/data/train/kDLzscQHXX.mp4
/data/train/xjZaHFkxLO.mp4
/data/train/QrLixlKwia.mp4
/data/train/cMHCmKBhrx.mp4
/data/train/ZsULxKAUpz.mp4
/data/train/MXUeAqCmJC.mp4
/data/train/EVBKJkGEgw.mp4
/data/train/XuvbQZnoRj.mp4
/data/train/ubDqLnnAKw.mp4
/data/train/SnOCEQuviQ.mp4
/data/train/LquywedhOB.mp4
/data/train/HrgFtHlGwu.mp4
/data/train/bqYXRyhROk.mp4
/data/train/nronqJuCWH.mp4
/data/train/dpvgoQJonR.mp4
/data/train/HKcdJoGbbX.mp4
/data/train/IEMXrhnRec.mp4
/data/train/uIQJvzlprd.mp4
/data/train/qUnXqWnFzA.mp4
/data/train/brgfMgRiEH.mp4
/data/train/ymYkuLSyOc.mp4
/data/train/kMhCMrMwYP.mp4
/data/train/auJLtHcZzr.mp4
/data/train/UhYSiHwdOw.mp4
/data/train/grUjqtShiP.mp4
/data/train/jAqCcnQqjH.mp4
/data/train/iWEZovjeaZ.mp4
/data/train/pHEIXRATpz.mp4
/data/train/bRxfmCHrkN.mp4
/data/train/ojjifCuJiF.mp4
/data/train/WGYJlviAKC.mp4
/data/train/DOIZdgMlkV.mp4
/data/train/FWCCUJsshl.mp4
/data/train/rFOctRFBaL.mp4
/data/train/LPGgHEzOxs.mp4
/data/train/pMjLhZtuqi.mp4
/data/train/IaIIazzpDt.mp4
/data/train/MKNyrWjntC.mp4
/data/train/gtTVCoLvTQ.mp4
/data/train/AmCxLBOOhU.mp4
/data/train/nXUEdgokxh.mp4
/data/train/dZzbeJHfUs.mp4
/data/train/wLyAmpnjFJ.mp4
/data/train/LhACyfXtqS.mp4
/data/train/bClXVWgMAA.mp4
/data/train/nTrPHsWKfr.mp4
/data/train/KtnmNloLyU.mp4
/data/train/LyMlvZOVQm.mp4
/data/train/zyqgjDpCLH.mp4
/data/train/jEFgTOlOJC.mp4
/data/train/KxyNtTJhBp.mp4
/data/train/zIpXJqsHxr.mp4
/data/train/wqxgrIWZPO.mp4
/data/train/fIRplGRMkf.mp4
/data/train/RtQUQvNscf.mp4
/data/train/TWIcKWghsH.mp4
/data/train/JLLxXBYLER.mp4
/data/train/DDjxAPVtfg.mp4
/data/train/pXGUWZciUL.mp4
/data/train/lVKaUTlejD.mp4
/data/train/VdhBHLcLXS.mp4
/data/train/bEJdeSYsmW.mp4
/data/train/ZeVjRrUdOo.mp4
/data/train/eqQHDXfjWD.mp4
/data/train/dSAYRusdYg.mp4
/data/train/tVrnFTOrMT.mp4
/data/train/PGGMRxYvhd.mp4
/data/train/fMCFLuTcSr.mp4
/data/train/DhWTSKfyHO.mp4
/data/train/tindEGTyAo.mp4
/data/train/nbOjQZEppD.mp4
/data/train/qpRQojOmPo.mp4
/data/train/heRORZelCU.mp4
/data/train/tKXpBnncHw.mp4
/data/train/HgFxXFjuTb.mp4
/data/train/znQEPuXLnl.mp4
/data/train/NbEAYyDRFf.mp4
/data/train/MRHofEUefK.mp4
/data/train/rUhnEEwwAv.mp4
/data/train/BFMPOHaMkz.mp4
/data/train/obTlTUSwKm.mp4
/data/train/qDzKxDwnSP.mp4
/data/train/BupMmIwBkq.mp4
/data/train/ECmQunduqE.mp4
/data/train/Vbcuwufitx.mp4
/data/train/VgTnaIVMUK.mp4
/data/train/wCZGmIejzH.mp4
/data/train/iSyQPDtXAA.mp4
/data/train/nAnGeCoVel.mp4
/data/train/SqKIOvahey.mp4
/data/train/fiIfEIEqwm.mp4
/data/train/UcnVKQxZDG.mp4
/data/train/jMALHoyETm.mp4
/data/train/BdTmhzAXJZ.mp4
/data/train/RdxHoKgDhK.mp4
/data/train/yftXLPvIgf.mp4
/data/train/dGOLsJhNKB.mp4
/data/train/dJzAZtmEin.mp4
/data/train/eHpfoaoZDM.mp4
/data/train/tAIgqNofsh.mp4
/data/train/PRYTKQOkvI.mp4
/data/val/OzXLcSCDxV.mp4
/data/val/kHqENFWPgf.mp4
/data/val/pSzCXTeAEq.mp4
/data/val/sCdHOopqLc.mp4
/data/val/TnsjBnwbIE.mp4
/data/val/qtejQnKwaH.mp4
/data/val/WAoztdmkqQ.mp4
/data/val/WJFjTJAEvg.mp4
/data/val/CKaznNHgkO.mp4
/data/val/vLZKocHwlS.mp4
/data/val/agqDTIEXbf.mp4
/data/val/kfpQrTayCJ.mp4
/data/val/zaHUTgJoNu.mp4
/data/val/gEmFLqlTtu.mp4
/data/val/uEZQeSthqv.mp4
/data/val/dDnAKKTTGe.mp4
/data/val/AEPjgECIVJ.mp4
/data/val/KHghpuduyq.mp4
/data/val/jtLonYJMWI.mp4
/data/val/VZaEGUGisX.mp4
/data/val/fkYiceJMLZ.mp4
/data/val/HXJPuAjkIA.mp4
/data/val/gPSyaOrdWb.mp4
/data/val/zTMTSAGWPs.mp4
/data/val/ELIhbxQCYp.mp4
/data/val/AOlqQrtAPr.mp4
/data/val/LDdnZocbhj.mp4
/data/val/TaXjOuHEcB.mp4
/data/val/MLzyJDnZai.mp4
/data/val/NmhTxMUwfU.mp4
/data/val/JDIhsbCmzy.mp4
/data/val/fMSxusghjR.mp4
/data/val/aKAycUbNZC.mp4
/data/val/lFrLiEQeXM.mp4
/data/val/mbLdzAfdlv.mp4
/data/val/arZqXonZMx.mp4
/data/val/piOolggPsl.mp4
/data/val/evfFfyiBAL.mp4
/data/test/JcJWjGJxfL.mp4
/data/test/GPdljUHzvw.mp4
/data/test/yknvKuQzqu.mp4
/data/test/jdRxShRmBE.mp4
/data/test/RhIUXqxonX.mp4
/data/test/ceGWyxFYOr.mp4
/data/test/YwrYfnmymh.mp4
/data/test/Vmotqojesq.mp4
/data/test/zvbFpuhDdi.mp4
/data/test/WeUxiPaqti.mp4
/data/test/NeiiTDMsdM.mp4
/data/test/pjTGiHRaMG.mp4
/data/test/CZiAVwkhYd.mp4
/data/test/kMBrCpDioD.mp4
/data/test/grenxmqNWn.mp4
/data/test/RjViBNCaeD.mp4
/data/test/ylWueLrBXS.mp4
/data/test/tmWRbdwGhT.mp4
/data/test/JjmhdnhoyH.mp4
/data/test/TNjWnwGaZq.mp4
/data/test/YyyVhJYkEA.mp4
/data/test/utgZohgAmm.mp4
/data/test/nhsSijtiAE.mp4
/data/test/NnokLnHVuH.mp4
/data/test/uyYsPcNWUd.mp4
/data/test/ufvVVaDbrx.mp4
/data/test/qgpTZEDnjU.mp4
/data/test/FWNwgSfyFg.mp4
/data/test/NCnpMDGGoe.mp4
/data/test/tLPvrnhDns.mp4
/data/test/LaoglOBmZc.mp4
/data/test/OWVRFVDZQc.mp4
/data/test/JWWHSlgcEh.mp4
/data/test/vtXZdeIAYz.mp4
/data/test/iaPnBUhqUi.mp4
/data/test/bPBjlzLqSu.mp4
/data/test/aRkzyBJjeu.mp4
/data/test/vybmfVoujX.mp4
/data/test/IVwLgitRrM.mp4
/data/test/smDOXhLlTe.mp4
/data/test/vytRODelyU.mp4
/data/test/DakKOVISIr.mp4
/data/test/yPbRWrMtqO.mp4
/data/test/rEBOwQAcjx.mp4
/data/test/zASKwYwQQs.mp4
/data/test/rOvYnHDBhh.mp4
/data/test/gVXGHgLZWG.mp4
/data/test/BHBqZdncZG.mp4
/data/test/pmEOJaSKtt.mp4
/data/test/xtnyCegcjK.mp4
/data/test/JieMzPRqGj.mp4
/data/test/vqqhHefhsC.mp4
/data/test/aoYreLKiIZ.mp4
/data/test/bouXbWrAZu.mp4
/data/test/MOVXvXgvLz.mp4
/data/test/WfpkVctTtq.mp4
/data/test/TJQmzWujQY.mp4
/data/test/tMVLeGMRHG.mp4
/data/test/tiDpoFALpi.mp4
/data/test/NSuLhzgMmD.mp4
/data/test/VXtopLLMFi.mp4
/data/test/rkpkPUymfc.mp4
/data/test/XubaLIWjfU.mp4
/data/test/cvhXMVpQVP.mp4
/data/test/qijUCpdZEl.mp4
/data/test/QWFoIqjjzt.mp4
/data/test/lmmTPksJpH.mp4
/data/test/yTEQcytKoF.mp4
/data/test/oQuMWDOdoU.mp4
/data/test/YLjOWLGVFq.mp4
/data/test/zILCfuWJGK.mp4
/data/test/cdacEtlqmy.mp4
/data/test/PkShqGrLOP.mp4
/data/test/WNFULxGjuq.mp4
/data/test/jExZlHaqBb.mp4
/data/test/SxptciOrUO.mp4
/data/test/OnhPOHzuGo.mp4
/data/test/bGgvgAWYDP.mp4
/data/test/VKgUATRonJ.mp4
/data/test/bLILtWsepi.mp4
/data/test/CDTwhBgOnp.mp4
/data/test/AiwfezlTZm.mp4
/data/test/LDvcAMqbOZ.mp4
/data/test/UtTJzqQRik.mp4
/data/test/FUTcjpinBd.mp4
/data/test/njMBTJojLl.mp4
/data/test/rhNjHsMWPo.mp4
/data/test/WLOuPiNWbp.mp4
/data/test/StDUoiHWEN.mp4
/data/test/dJDPLYmiAA.mp4
/data/test/WjnkpdiLkQ.mp4
/data/test/vGHquxAbkH.mp4

**Comment by ycybiubiu** [comment] 2022-07-26 08:49
Hello,I downloaded the data three more times, and checked the data downloaded one by one, each time it is the video error listed in the attachment, which can basically rule out the network problem, please check again, thank you.

**Comment by bapmbr** [comment] 2022-07-27 10:21
We are currently checking this. We will figure out a solution.
Thanks!

**Comment by bapmbr** [comment] 2022-07-28 13:01
Hi!

We have addressed this issue and came up with the following:
- There are some videos from Kinetics400ViPriors dataset that are corrupted. We do not know why, but we do know they are very few. In total, between all subsets, about 300 videos. The dataset has about 70k videos.
- We have updated the repo considering this issue so please check it. You will find more information and some new guidelines.
- We have added some code to check the files you get after downloading the Kinetics400ViPriors dataset.
- You can check the list of videos that are blocked
- Those videos are not considered during the evaluation, as you can see in the updates applied to the evaluation code kit. If you have labels for the blocked videos, they will just be ignored.
- The CodaLab server has been updated to consider this situation.

Please, if you find any other issue tell us and we will address it as soon as posible.

**Comment by bapmbr** [comment] 2022-07-28 13:06
@ycybiubiu thanks a lot for helping us with this.
We would appreciate a lot if you could check it and tell us if everything works now :)

**Comment by ycybiubiu** [comment] 2022-07-28 13:11
Okay, I check it later and keep in touch


---Original---
From: ***@***.***&gt;
Date: Thu, Jul 28, 2022 21:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [VIPriors/vipriors-challenges-toolkit] Action Recognition -Corrupted Videos [SOLVED] (Issue #58)




 
@ycybiubiu thanks a lot for helping us with this.
 We would appreciate a lot if you could check it and tell us if everything works now :)

**Comment by bapmbr** [comment] 2022-08-08 10:43
Closing this issue as there have not been any comment to the solution provided.

**Closed as completed by bapmbr** 2022-08-08 10:43 UTC
